import Head from 'next/head'
import { useRouter } from 'next/router'

const Home = () => {
  const router = useRouter();
  return (
    <div className="bg-blackblue text-white">
      <Head>
        <title>TicTacToe-Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex flex-col">
        <div className="text-center m-auto">
          <p className="text-5xl text-gold font-bold font-heading text-center mb-20">Welcome to TicTacToe!</p>
          <div className="flex justify-center">
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
          </div>
          <div className="flex justify-center">
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
          </div>
          <div className="flex justify-center">
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
            <a className="border border-yellow-500 p-8 py-7 hover:bg-blue-100"> </a>
          </div>
          <p className=" text-yellow-500 mt-10 mb-6">This is a 2 player local game, so grab a friend and let's get started!</p>
          <button onClick={() => router.push('/game')} className="bg-yellow-500 text-white p-10 py-2 rounded mt-8 border-2 border-yellow-500 hover:bg-white hover:text-yellow-500 ">Go</button>
        </div>
      </div>
    </div>
  )
}

export default Home






